### ISSUE TITLE
bug(payload-indexer): Typesense outage shows all documents as "not-indexed" instead of "error"

### ISSUE THREAD

**Issue by Fiser12** [Zetesis-Labs/PayloadAgents#107]
## Problem

In `getIndexedHashes`, per-document errors are caught and logged with `logger.warn`, but the document is **excluded from the result Map**. Downstream in `checkBatchSyncStatus`, a missing entry is interpreted as `'not-indexed'` (line 190).

During a Typesense outage, **all documents would appear as "not-indexed"** in the admin list view, which is misleading. The admin might think the index is empty when it's actually a connectivity issue.

**Files**:
- `packages/payload-indexer/src/sync-status/sync-status-service.ts:57-58` — `getIndexedHashes` returns empty Map when adapter lacks `searchDocumentsByFilter`
- `packages/payload-indexer/src/sync-status/sync-status-service.ts:75-79` — per-document errors silently omit entry
- `packages/payload-indexer/src/sync-status/sync-status-service.ts:190` — missing entry = `'not-indexed'`

Note: the single-document path (`checkSyncStatus`) correctly returns `'error'` with a descriptive message (line 109-115), but the batch path doesn't.

## Fix

Distinguish between "not found in index" and "failed to check index":

1. In `getIndexedHashes`: when a lookup fails, store a sentinel value (e.g., `'__error__'`) instead of omitting the entry
2. In `checkBatchSyncStatus`: check for the sentinel and set status to `'error'` instead of `'not-indexed'`
3. When `searchDocumentsByFilter` is undefined: return `'error'` for all documents (matching single-doc behavior)

## Context

Introduced in PR #104.
